name: Code Validation

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  validate_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm install

      - name: Validate HTML
        run: npm run htmlhint > npm run htmlhint > htmlhint_errors.txt 2>&1 || true

      - name: Display HTMLHint Errors in Markdown
        run: |
          echo "## HTML errors : :page_with_curl:" >> $GITHUB_STEP_SUMMARY
          cat htmlhint_errors.txt >> $GITHUB_STEP_SUMMARY

      - name: Validate CSS
        run: npm run stylelint npm run stylelint > stylelint_errors.txt 2>&1 || true

      - name: Display Stylelint Errors
        run: |
          echo "## CSS errors : :art:" >> $GITHUB_STEP_SUMMARY
          cat stylelint_errors.txt >> $GITHUB_STEP_SUMMARY
